### ISSUE TITLE
Unable to generate documentation

### ISSUE THREAD

**Issue by dheerajpanyam** [jedelman8/ansible-webdocs#2]
Hi ,

 I am trying to generate the markdown for a custom module that i wrote, the module follows the Ansible standards in documentation and i do not suspect anything wrong here. It is creating a markdown with empty content ( just the header and the sub-header). The module path etc is set correctly in my playbook used to generate the markdown.

I am using ansible 1.8.4

Please help

vagrant@vagrant-ubuntu-trusty-64:~/ansible-webdocs/ansible-webdocs$ ansible-playbook create-ansible-webdoc.yml -i /home/vagrant/playbooks/inventory

PLAY [create local markdown doc] **********************************************

TASK: [get docs and examples for modules] *************************************
ok: [localhost]

TASK: [build web/markdown ansible docs] ***************************************
changed: [localhost]

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0

vagrant@vagrant-ubuntu-trusty-64:~/ansible-webdocs/ansible-webdocs$ cd web/
vagrant@vagrant-ubuntu-trusty-64:~/ansible-webdocs/ansible-webdocs/web$ vi ansiblefilesdoc.md
vagrant@vagrant-ubuntu-trusty-64:~/ansible-webdocs/ansible-webdocs/web$

Below is the markdown that got generated
# Ansible module for Vistara Maintenance
### _Schedule a Vistara Maintenance Window_

---
### Requirements
- See official Ansible docs

---
### Modules

---

---

Created by Jason Edelman. February 2015.

**Comment by jedelman8** [comment]
Can you pull it down again and re-try?  I just pushed a fix for another
issue.

Thanks,
Jason

**Comment by dheerajpanyam** [comment]
I pulled the latest version again and tried but still not generating the complete documentation. I have validated my custom module for the comments i added  for the documentation using YAMLIint and it returned fine .

Regards
Dheeraj

**Comment by jedelman8** [comment]
Can you post your module ?  If you prefer not to post here, email it to me
at jedelman8 @ gmail dot com.

**Comment by dheerajpanyam** [comment]
Below is the YAML portion of the module , following it is the actual python module code which is implemented in a OO fashion .

#!/usr/bin/env python
import requests
import json
from datetime import datetime,timedelta
#from dateutil import tz

## DOCUMENTATION = '''

module: Vistara_Maintenance
short_description: Schedule a Vistara Maintenenance window
description:
- Schedules a Vistara Maintenance window for a specific set of devices/Device Groups with a starttime and endtime in the specified timezone
  version_added: "1.0"
  author: Dheeraj Panyam
  options:
  # One or more of the following
  name:
    description:
      - Name for the maintenance 
    required: false 
    default: Created By Ansible
  description:
    description:
      - Describes what the maintenance is intended for
    required: false 
  schedule_type:
    description:
  - Describes the maintenance type 
    required: true
    aliases: ['type','maint_type']
    choices: ['One-Time']
    devices:
    description:
  - Comma seperated list of devices to be put to maintenance, one of the parameters devices or devicegroups need to be given as input 
    required: false if devicegroups option is used 
    aliases: ['dev']
    devicegroups:
    description:
  - Comma seperated list of device groups to be put to maintenance, one of the parameters devices or devicegroups need to be given as input 
    required: false if devices option is used 
    aliases: ['devgrp']
    start_time:
    description:
  - Specifies the start time for the maintenance window in the specified timezone 
    required: true
    aliases: ['start']
    end_time:
    description:
  - Specifies the end time for the maintenance window in the specified timezone 
    required: true
    aliases: ['end']
    timezone:
    description:
  - Specifies the timezone  for the maintenance window  
    required: true
    default: ['America/Los_Angeles']
    aliases: ['zone']
    client_id:
    description:
  - Specifies the tenant Id  
    required: true
    '''  

EXAMPLES = '''

# Schedule a 30 min Vistara Maintenenance window containing 2  devicegroups and 3 devices for client Netenrich Internal in the IST timezone from 3pm to 3:30pm
- vistara_maintenance: schedule_type:One-Time devices:HYDLPT326,HYDLPT104 devicegroups:'Test Group,test1' start_time:2015-06-01T23:15:00+0000 end_time:2015-06-01T15:30:00+0000 timezone:Asia/Calcutta client_id:client_2655

# Schedule a 3hr 15min Vistara Maintenenance window for a desktop device in the Netenrich Internal domain from 6pm to 9:15pm
- vistara_maintenance: schedule_type:One-Time devices:HYDPC010 start_time:2015-06-01T18:00:00+0000 end_time:2015-06-01T21:15:00+0000 timezone:Asia/Calcutta client_id:client_2655
  '''

**Comment by jedelman8** [comment]
Can you please post it in a code block like so:

```
INSERT YOUR CODE HERE
```

This way, I can see the proper layout.

**Comment by dheerajpanyam** [comment]
Sorry i realised it later that it was actually rendering the markdown but the code is missing 

#!/usr/bin/env python
import requests
import json
from datetime import datetime,timedelta
#from dateutil import tz

DOCUMENTATION = '''
---
module: Vistara_Maintenance
short_description: Schedule a Vistara Maintenenance window
description:
 - Schedules a Vistara Maintenance window for a specific set of devices/Device Groups with a starttime and endtime in the specified timezone
version_added: "1.0"
author: Dheeraj Panyam
options:
# One or more of the following
  name:
    description:
      - Name for the maintenance 
    required: false	
    default: Created By Ansible
  description:
    description:
      - Describes what the maintenance is intended for
    required: false	
  schedule_type:
    description:
     - Describes the maintenance type 
    required: true
    aliases: ['type','maint_type']
    choices: ['One-Time']
  devices:
    description:
     - Comma seperated list of devices to be put to maintenance, one of the parameters devices or devicegroups need to be given as input 
    required: false if devicegroups option is used 
    aliases: ['dev']
  devicegroups:
    description:
     - Comma seperated list of device groups to be put to maintenance, one of the parameters devices or devicegroups need to be given as input 
    required: false if devices option is used 
    aliases: ['devgrp']
  start_time:
    description:
     - Specifies the start time for the maintenance window in the specified timezone 
    required: true
    aliases: ['start']
  end_time:
    description:
     - Specifies the end time for the maintenance window in the specified timezone 
    required: true
    aliases: ['end']
  timezone:
    description:
     - Specifies the timezone  for the maintenance window  
    required: true
    default: ['America/Los_Angeles']
    aliases: ['zone']
  client_id:
    description:
     - Specifies the tenant Id  
    required: true
''' 	

EXAMPLES = '''
# Schedule a 30 min Vistara Maintenenance window containing 2  devicegroups and 3 devices for client Netenrich Internal in the IST timezone from 3pm to 3:30pm 
- vistara_maintenance: schedule_type:One-Time devices:HYDLPT326,HYDLPT104 devicegroups:'Test Group,test1' start_time:2015-06-01T23:15:00+0000 end_time:2015-06-01T15:30:00+0000 timezone:Asia/Calcutta client_id:client_2655

# Schedule a 3hr 15min Vistara Maintenenance window for a desktop device in the Netenrich Internal domain from 6pm to 9:15pm 
- vistara_maintenance: schedule_type:One-Time devices:HYDPC010 start_time:2015-06-01T18:00:00+0000 end_time:2015-06-01T21:15:00+0000 timezone:Asia/Calcutta client_id:client_2655
'''

**Comment by dheerajpanyam** [comment]
Sorry i realised it later that it was rendering the YAML code i pasted into a markdown , how do i post it in a code block?

Dheeraj

**Comment by jedelman8** [comment]
Use the character to the right of the "1" on the keyboard, i.e. the backtick "`" like so:

Three backticks: "```"  without the quotes, the paste your code/yaml, and then close it with three more backticks.

Also see this: https://help.github.com/articles/markdown-basics/#code-formatting

**Comment by dheerajpanyam** [comment]
Thanks , i am a newbie to git below is the YAML portion of the Ansible module

```
DOCUMENTATION = '''
---
module: Vistara_Maintenance
short_description: Schedule a Vistara Maintenenance window
description:
 - Schedules a Vistara Maintenance window for a specific set of devices/Device Groups with a starttime and endtime in the specified timezone
version_added: "1.0"
author: Dheeraj Panyam
options:
# One or more of the following
  name:
    description:
      - Name for the maintenance 
    required: false 
    default: Created By Ansible
  description:
    description:
      - Describes what the maintenance is intended for
    required: false 
  schedule_type:
    description:
     - Describes the maintenance type 
    required: true
    aliases: ['type','maint_type']
    choices: ['One-Time']
  devices:
    description:
     - Comma seperated list of devices to be put to maintenance, one of the parameters devices or devicegroups need to be given as input 
    required: false if devicegroups option is used 
    aliases: ['dev']
  devicegroups:
    description:
     - Comma seperated list of device groups to be put to maintenance, one of the parameters devices or devicegroups need to be given as input 
    required: false if devices option is used 
    aliases: ['devgrp']
  start_time:
    description:
     - Specifies the start time for the maintenance window in the specified timezone 
    required: true
    aliases: ['start']
  end_time:
    description:
     - Specifies the end time for the maintenance window in the specified timezone 
    required: true
    aliases: ['end']
  timezone:
    description:
     - Specifies the timezone  for the maintenance window  
    required: true
    default: ['America/Los_Angeles']
    aliases: ['zone']
  client_id:
    description:
     - Specifies the tenant Id  
    required: true
'''     

EXAMPLES = '''
# Schedule a 30 min Vistara Maintenenance window containing 2  devicegroups and 3 devices for client Netenrich Internal in the IST timezone from 3pm to 3:30pm 
- vistara_maintenance: schedule_type:One-Time devices:HYDLPT326,HYDLPT104 devicegroups:'Test Group,test1' start_time:2015-06-01T23:15:00+0000 end_time:2015-06-01T15:30:00+0000 timezone:Asia/Calcutta client_id:client_2655

# Schedule a 3hr 15min Vistara Maintenenance window for a desktop device in the Netenrich Internal domain from 6pm to 9:15pm 
- vistara_maintenance: schedule_type:One-Time devices:HYDPC010 start_time:2015-06-01T18:00:00+0000 end_time:2015-06-01T21:15:00+0000 timezone:Asia/Calcutta client_id:client_2655
'''
```
